### ISSUE TITLE
An inconsistency in highlighting

### ISSUE THREAD

**Issue by fredrik-bakke** [fizruk/vscode-rzk#11]
In the following two equivalent definitions, one has `∑` highlighted as `variable.parameter.rzk` while the other has it highlighted as `entity.name.type.rzk`.
<img width="458" alt="image" src="https://github.com/fizruk/vscode-rzk/assets/5176294/f7b18b0e-2567-47fd-ab9c-04f367f6b679">

Presumably, the highlighter matches the opening parenthesis and thinks it's matching a parameter declaration `(x : A)` or something like this. If this is the case, then the issue can be resolved for one-liners with a recursive pattern.

**Comment by fizruk** [comment]
I wonder if it makes sense to fix this (and #10) or wait for the proper semantic highlighting.

**Comment by fredrik-bakke** [comment]
Understandable. Would you mind publishing the current version then? I would personally benefit from having parentheses rainbow-highlighted and the proper keybinding for commenting code at the very least 😅

**Comment by fizruk** [comment]
Absolutely, release is on the way!

**Comment by fizruk** [comment]
Should be fixed with semantic highlighting now (works on my machine).
