### ISSUE TITLE
Add locally installed rzk to PATH in VS Code Terminal

### ISSUE THREAD

**Issue by fizruk** [fizruk/vscode-rzk#27]
Locally installing `rzk` is not enough if one wants to use it in the terminal, so it would be nice to have `rzk` available in the Terminal, at least locally.

**Comment by fizruk** [comment]
See https://github.com/emilyriehl/yoneda/issues/14#issuecomment-1622408998 for an example of confusion with the current implementation.

**Comment by aabounegm** [comment]
I believe it should be possible, similar to the way the Python extension automatically activates the virtual environment in the terminal if it detects one, but I have to explore how they do it exactly.

**Comment by aabounegm** [comment]
Never mind, turned out to be rather simple (but not the way Python does it). Please double check that it works on Mac (it worked on Windows with PowerShell, Git Bash, and WSL): #30.
