### ISSUE TITLE
Incremental type checking

### ISSUE THREAD

**Issue by aabounegm** [fizruk/vscode-rzk#38]
Any language server should be able to handle partially written programs to display feedback as the program is being written rather than once at the end. That involves parsing errors that should be handled gracefully and being able to update the type checking result based on incremental changes to the source code instead of type-checking the whole module from scratch on every keystroke (if I understand it correctly).

These resource might be useful (I didn't check in details yet):
- [A logical framework for incremental type-checking](https://cedric.cnam.fr/~puechm/slides-cea.pdf) (Slides)
- [Incremental type-checking for free: using scope graphs to derive incremental type-checkers](https://dl.acm.org/doi/abs/10.1145/3563303) (Paper - 2022)
- [A systematic approach to deriving incremental type checkers](https://dl.acm.org/doi/10.1145/3428195) (Paper - 2020)
  - [Video presentation of the paper above](https://www.youtube.com/watch?v=1lL5KGVqMos) (YouTube)
- [Incremental Type-Checking for Type-Reflective Metaprograms](https://www.researchgate.net/publication/216793786_Incremental_Type-Checking_for_Type-Reflective_Metaprograms) (Paper - 2010)
- [How would you design a compiler upfront to be both a compiler and a LSP server?](https://langdev.stackexchange.com/questions/915/how-would-you-design-a-compiler-upfront-to-be-both-a-compiler-and-a-lsp-server) (StackExchange)

**Comment by fizruk** [comment]
Closing since it is handled (partially for now) in the Rzk itself.
