### ISSUE TITLE
Handle multi-module projects

### ISSUE THREAD

**Issue by aabounegm** [fizruk/vscode-rzk#39]
While `rzk` doesn't have an `import` command yet (https://github.com/rzk-lang/rzk/issues/17) to declare dependencies among modules, the type-checker supports specifying more than one file which would all be considered together.
Currently, the extension deals with every file in isolation of the other files, but some files might use symbols defined in other files, leading to false positive type errors from the extension.

There should be a config file (maybe `rzk.yaml`?) that identifies a rzk project and lists all the files included in it, which will be used by the extension to consider all of the listed modules at once. As an added bonus, it could also be used by the CLI in case no file paths were given (the same way TypeScript refers to `tsconfig.json` if no input files were passed).

Additionally, a warning should be issued on any open file that is not listed in the projects `included-files` files, and to silence the warning the user should explicitly list it in `excluded-files`.

Glob support is optional but highly recommended (perhaps in a separate issue).
I also think it will be cool if `rzk`'s CLI has a command to generate such file automatically (similar to `tsc --init`)

**Comment by fizruk** [comment]
Fixed in #36.
