### ISSUE TITLE
Replace common ASCII sequences with their Unicode equivalent

### ISSUE THREAD

**Issue by aabounegm** [fizruk/vscode-rzk#40]
Most importantly, the ones listed in the [yoneda formalization style guide](https://github.com/emilyriehl/yoneda/blob/a161e654021b7616e51a787e695eddce8529ea4d/STYLEGUIDE.md#use-of-unicode-characters).
Of course, this should be behind a config setting in case it is inconvenient for some users. The default setting should be `on` (I think)

**Comment by fizruk** [comment]
This can be done on save and every time (when at least one substitution took place) there should be a pop-up explaining what just happened with options:
1. Do not show (this message) again.
2. Disable the feature.

**Comment by aabounegm** [comment]
> This can be done on save

Wouldn't it be better to replace as it is written to avoid lots of changes at once (which can be confusing)?

Also, would it be desirable to replace LaTeX sequences as well, or just the ASCII ones in the style guide? In other words, do we want to integrate all the functionality of the [Unicode Latex](https://marketplace.visualstudio.com/items?itemName=oijaz.unicode-latex) extension into our extension? If so, do we reimplement them or just publish an [Extension Pack](https://code.visualstudio.com/blogs/2017/03/07/extension-pack-roundup) that includes that extension?

**Comment by paigenorth** [comment]
For me, I would like the functionality of Unicode Latex.

**Comment by aabounegm** [comment]
This has been implemented in #66 and https://github.com/rzk-lang/rzk/pull/144. The full functionality of _Unicode LaTeX_ has **not** been integrated (only the symbols listed in the style guide), so it might still be useful to have that extension installed for use in identifier names.
