### ISSUE TITLE
Autocomplete weirdness

### ISSUE THREAD

**Issue by paigenorth** [fizruk/vscode-rzk#47]
In the exercises for the Regensburg school, when I type `2-to` and the `RET` it autocompletes to `2-2-to-Σ`.

**Comment by fizruk** [comment]
For context: this happens with https://github.com/fizruk/itp-school-2023-demo and `2-to` should be completed to `2-to-Σ`, not `2-2-to-Σ`.

This is most likely because the extension does not know that `-` can be a part of the identifier. We should be able to fix that easily @aabounegm

**Comment by fizruk** [comment]
Fixed in #49.
