### ISSUE TITLE
Unicode entry

### ISSUE THREAD

**Issue by paigenorth** [fizruk/vscode-rzk#48]
I don't get unicode entry in the way that I thought should be available. For instance, when I write `\mapsto`, it doesn't change this to ↦ or suggest a ↦.

I'm using vscode-rzk 0.4.0 and VS Code 1.82.2 on a Mac.

**Comment by aabounegm** [comment]
Yes, this is not supported yet but we plan to add this feature. For discussion, see #40.
In the meanwhile, you can check out the [Unicode Latex](https://marketplace.visualstudio.com/items?itemName=oijaz.unicode-latex) extension.

**Comment by paigenorth** [comment]
Ah sorry! 😶

**Comment by aabounegm** [comment]
No worries 🙂
