### ISSUE TITLE
Updating broken on Linux

### ISSUE THREAD

**Issue by aabounegm** [fizruk/vscode-rzk#60]
https://rzk-lang.zulipchat.com/#narrow/stream/407303-dev-rzk/topic/vscode.20on.20linux

I assume it's because the language server is using the binary file, causing a `Permission denied` when trying to replace it, but I need to add logs to confirm this.
If so, the solution would likely be to just stop the LSP client.

**Comment by fizruk** [comment]
> If so, the solution would likely be to just stop the LSP client.

There could be other reasons, and if replacing a file (or any other part of the update process) fails, the client should be notified about the failure and, perhaps, we should also suggest something in that case (remove local installation via extension or manually, submit an issue here, etc.).
